exclude_paths:
  - db/**/*
  - spec/support/auth_helper.rb

detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  FeatureEnvy:
    enabled: false

  UtilityFunction:
    public_methods_only: true
