exclude_paths:
  - db/**/*
  - spec/support/auth_helper.rb

directories:
  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
  'app/forms':
    Attribute:
      enabled: false

detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  FeatureEnvy:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  TooManyStatements:
    max_statements: 10
