require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.2
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - lib/tasks/cucumber.rake
    - node_modules/**/*
    - bin/bundle
    - db/schema.rb
    - config/initializers/*
    - config/environments/**/*
    - spec/factories/*
    - db/**/*

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - and

RSpec/DescribeClass:
  Exclude:
    - spec/tasks/**/*

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

Rails/SkipsModelValidations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Max: 4

Metrics/AbcSize:
  Max: 20

Style/MixinUsage:
  Exclude:
    - features/support/devise.rb
    - features/support/env.rb
